### ISSUE TITLE
Static Files Error With The Latest Version (3.3.2)

### ISSUE THREAD

**Issue by StingBolt** [django/asgiref#251]
There seems to be something wrong with serving static files in the latest version, this is the error:
```
raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
HTTP GET /static/rest_framework/js/default.js 500 [1.01, 127.0.0.1:50017]
```
The previous version (3.3.1) works perfectly

**Comment by carltongibson** [comment]
@StingBolt Can you paste the full traceback please? Also can you say if you're using this just with Django or with Channels or with..., and so on? — Context is all here. 🙂

Thanks

Refs https://github.com/django/django/pull/14221

**Comment by BeryJu** [comment]
I also just ran into this issue, same error message:
```
Traceback (most recent call last):
  File "/Users/langhammerj/.local/share/virtualenvs/authentik-fAhVAmau/lib/python3.9/site-packages/channels/staticfiles.py", line 40, in __call__
    return await self.staticfiles_handler_class()(
  File "/Users/langhammerj/.local/share/virtualenvs/authentik-fAhVAmau/lib/python3.9/site-packages/channels/staticfiles.py", line 56, in __call__
    return await super().__call__(scope, receive, send)
  File "/Users/langhammerj/.local/share/virtualenvs/authentik-fAhVAmau/lib/python3.9/site-packages/channels/http.py", line 198, in __call__
    await self.handle(scope, async_to_sync(send), body_stream)
  File "/Users/langhammerj/.local/share/virtualenvs/authentik-fAhVAmau/lib/python3.9/site-packages/asgiref/sync.py", line 105, in __init__
    raise TypeError("async_to_sync can only be applied to async functions.")
TypeError: async_to_sync can only be applied to async functions.
```
(In my case, using Django 3.1.7, asgiref 3.3.2 and channels 3.0.3, and downgrading to 3.3.1 fixes it here too)

**Comment by KristobalJunta** [comment]
I'm not familiar with REST framework code there, but the issue can be related to how `functools.partial` works on Python < 3.8.

See this SO answer for details - https://stackoverflow.com/a/52422903.

Got a related bug in another library today - https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/68

**Comment by yedpodtrzitko** [comment]
So just to narrow this issue down, the culprit is `not asyncio.iscoroutinefunction(awaitable)` here: https://github.com/django/asgiref/commit/7921bf04dfa71cebc9294e8f06936cdb63166674#diff-6af8b5512d949418a62aa4e6be5c741b376f69feacf7cc5e3fe57162aaba1650R104

**Comment by pgjones** [comment]
I've seen this bug in Quart (I think), [here is a fix](https://gitlab.com/pgjones/quart/-/blob/master/src/quart/utils.py#L104)

**Comment by yedpodtrzitko** [comment]
Quartz code:
```
 if sys.version_info >= (3, 8):
        return asyncio.iscoroutinefunction(func)
```

...however I'm encountering this issue even with Python 3.9.1

**Comment by andrewgodwin** [comment]
The issue is fixed on `main`, I'll get a 3.3.3 release out today as well.

**Comment by jaknel** [comment]
This bug is not resolved for me despite upgrading to 3.3.3.

Django 3.2
Channels 3.0.3
asgiref 3.3.3
daphne 3.0.1

It looks like a lambda created by daphne at https://github.com/django/daphne/blob/main/daphne/server.py#L206 is what eventually ends up in https://github.com/django/asgiref/blob/main/asgiref/sync.py#L120 as `awaitable` and fails `inspect._has_code_flag(awaitable, inspect.CO_COROUTINE)`

**Comment by andrewgodwin** [comment]
Yup, I think you're right. I'm going to go change the error to a warning for now, async functions are too hard to reliably detect in Python.

**Comment by andrewgodwin** [comment]
3.3.4 is out which replaces this error with a warning, so your applications will still run. We'll have to figure out how to get that Daphne lambda to "look async", or maybe just abandon the whole idea of detecting coroutine-yielding callables before the fact entirely.

**Comment by carltongibson** [comment]
Hey @andrewgodwin — thanks for your work on this! 

This all went very quickly yesterday, and with the Django 3.2 release I didn't have the bandwidth to follow totally. I was looking at a quick release for Daphne today, but with asgiref 3.3.4 out, I will take a few days to fully work through it, and look to release next week. 

> We'll have to figure out how to get that Daphne lambda to "look async"...

We have https://github.com/django/daphne/pull/364 proposed, to use a `partial` instead of the lambda.

**Comment by andrewgodwin** [comment]
Yes, let's take the time and do this properly. Given we know that `partial` works and is accounted for in both python and asgiref, I think I'd go with that?
